### ISSUE TITLE
Luxon migration issue

### ISSUE THREAD

**Issue by BnitoBzh** [ember-cli-deploy/ember-cli-deploy-display-revisions#40]
i get this error with luxon when i run `ember deploy:list` command

`Error: fromMillis requires a numerical input, but received a string with value 2020-09-22T15:40:08.032Z`

**Comment by achambers** [comment]
Whoops. 

@kpfefferle Fancy jumping in here?

**Comment by kpfefferle** [comment]
@BnitoBzh @achambers On it!

**Comment by kpfefferle** [comment]
@BnitoBzh Which ember-cli-deploy index plugin are you using? I'm having a hard time reproducing this since my index plugin seems to provide a timestamp in milliseconds as ember-cli-deploy-display-revisions expects ([see the README here](https://github.com/ember-cli-deploy/ember-cli-deploy-display-revisions#passing-revisions)).

Moment.js was certainly more forgiving (to a fault) on the format of timestamp when parsing even though the README documents that this plugin expects a timestamp in milliseconds. It's absolutely possible to make this plugin accept other formats as well, but covering absolutely everything that Moment could parse may get a bit complex. If there are a ton of index plugins (or a couple popular ones) that are providing ISO 8601 instead of milliseconds, then maybe this plugin might want to accept that format too - or maybe we could fix the upstream index plugins so they provide milliseconds as expected?

**Comment by BnitoBzh** [comment]
hi @kpfefferle, I have no particular `display-revisions`config.
i use ember-cli-deploy@^1.0.2 and ember-cli-deploy-lightning-pack@^3.0.0

my lock is (`yarn list | grep deploy`)
```
├─ ember-cli-deploy-build@2.0.0
│  ├─ ember-cli-deploy-plugin@^0.2.1
├─ ember-cli-deploy-display-revisions@2.1.0
│  ├─ ember-cli-deploy-plugin@^0.2.3
├─ ember-cli-deploy-gzip@1.0.1
│  ├─ ember-cli-deploy-plugin@^0.2.6
├─ ember-cli-deploy-lightning-pack@3.0.2
│  ├─ ember-cli-deploy-build@^2.0.0
│  ├─ ember-cli-deploy-display-revisions@^2.0.0
│  ├─ ember-cli-deploy-gzip@^1.0.0
│  ├─ ember-cli-deploy-manifest@^1.0.0
│  ├─ ember-cli-deploy-redis@^2.0.0
│  ├─ ember-cli-deploy-revision-data@^1.0.0
│  └─ ember-cli-deploy-s3@^2.0.0
├─ ember-cli-deploy-manifest@1.1.0
│  ├─ ember-cli-deploy-plugin@^0.2.3
├─ ember-cli-deploy-plugin@0.2.9
├─ ember-cli-deploy-progress@1.3.0
├─ ember-cli-deploy-redis@2.0.0
│  ├─ ember-cli-deploy-plugin@^0.2.9
├─ ember-cli-deploy-revision-data@1.0.0
│  ├─ ember-cli-deploy-plugin@^0.2.6
├─ ember-cli-deploy-s3@2.0.0
│  ├─ ember-cli-deploy-plugin@^0.2.2
├─ ember-cli-deploy@1.0.2
│  ├─ ember-cli-deploy-progress@^1.3.0
```

**Comment by kpfefferle** [comment]
@BnitoBzh That's helpful info, thanks. I'll investigate to see which of those plugins is implementing the `fetchRevisions` hook 👀

**Comment by BnitoBzh** [comment]
probably `ember-cli-deploy-redis` all my deployments are pushed to redis (index.html), and s3 (all files).
when i add this deploy config :
```javascript
    'display-revisions': {
      revisions: function (context) {
        console.log(context.revisions);
        return context.revisions;
      }
    }
```
the `ember deploy:list qa` command will log:
```javascript
[
  {
    revision: '0.11.5+25c3f241',
    active: true,
    revisionData: {
      revisionKey: '0.11.5+25c3f241',
      timestamp: '2020-10-02T11:28:17.192Z',
      scm: [Object]
    }
  },
  {
    revision: '0.11.5+c3aa08d3',
    active: false,
    revisionData: {
      revisionKey: '0.11.5+c3aa08d3',
      timestamp: '2020-09-22T15:40:08.032Z',
      scm: [Object]
    }
  },
// ....
```

**Comment by kpfefferle** [comment]
It appears that the root of this issue is that [ember-cli-deploy-revision-data uses ISO 8601 format for its timestamp](https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/blob/b71afd74ca443fb0be36e1eb0a66461abf981eda/lib/data-generators/git-commit.js#L21) while ember-cli-deploy-display-revisions expects a timestamp in milliseconds. This seems like a pretty significant disconnect in the ember-cli-deploy ecosystem, and it's probably a tangled web of plugins that expect one or the other (or allow both).

At least this gives me some confidence that if this plugin were to support ISO 8601 in addition to milliseconds, that may be enough of a fix to expect most issues to be resolved for the time being. I'll open a PR to do this.

**Comment by achambers** [comment]
> It appears that the root of this issue is that [ember-cli-deploy-revision-data uses ISO 8601 format for its timestamp](https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/blob/b71afd74ca443fb0be36e1eb0a66461abf981eda/lib/data-generators/git-commit.js#L21) while ember-cli-deploy-display-revisions expects a timestamp in milliseconds. This seems like a pretty significant disconnect in the ember-cli-deploy ecosystem, and there's likely a tangled web of plugins that expect one or the other or allow either.
> 
> At least this gives me confidence that if this plugin supported ISO 8601 in addition to milliseconds, that may be enough of a fix to expect most issues to be resolved for the time being. I'll open a PR to do this.

Thanks a million for diving in @kpfefferle . I’ll merge and release when ready.
